pipeline {
    agent any
    environment {
        maven-image = "maven:3-openjdk-11-slim"
    }
    stages {
        stage('Build') {
            agent {
                docker {
                    image "${maven-image}"
                    args '-v $HOME/.m2:/root/.m2'
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
            post {
                success {
                    echo "${STAGE_NAME} success!!!"
                }
                failure {
                    echo "${STAGE_NAME} failed :( "
                }
            }
        }
        stage('Test') {
            agent {
                docker {
                    image "${maven-image}"
                    args '-v $HOME/.m2:/root/.m2'
                }
            }
            steps {
                sh 'mvn test'
                jacoco()
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            agent {
                docker {
                    image "${maven-image}"
                    args '-v $HOME/.m2:/root/.m2'
                }
            }
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
            post {
                always {
                    archiveArtifacts artifacts: 'target/*.jar', followSymlinks: false
                }
            }
        }
    }
}
